### ISSUE TITLE
"Invalid server answer, check URL" with owncloud on Android 4.3

### ISSUE THREAD

**Issue by ulno** [gggard/AndroidCaldavSyncAdapater#87] opened 2013-08-25 16:24 UTC
This might be a duplicate of issue #9 so feel free to merge if this is better.
I am trying to connect to my owncloud server and tried to use the .../principals/my_user url scheme. However, I always get a "Invalid server answer, check URL". Is there an easy way to provide more information?

I tried 1.7 from Android play store and fdroid as well as timonberger's 1.8-alpha build from issue #86. All having the same effect. My phone is a Nexus 4 running cyanogenmod 10.2 nightly (Android 4.3).

If I can provide more help or clues with a compiled version, and it is easy to build this in eclipse, I will clone the git repository and give it a go.

Cheers,
Ulrich

**Comment by timoberger** [comment] 2013-08-26 07:10
Hello ulno,

please check if you can access the following calendar.
user: test
pass: test
url: http://demo.owncloud.org/remote.php/caldav/calendars/test/owncloud_android

i added this calendar successful to my device.

**Comment by timoberger** [comment] 2013-08-26 07:14
owncloud seems to be using SabreDAV which i am using also (without owncloud).

**Comment by ulno** [comment] 2013-08-26 10:46
Hi Timo,
After getting several times the password is incorrect and then trying to directly connect with the browser to owncloud, I now added the demo calendar. It also seems to sync. I see the calendar in Android as well as also the test events.
So, probably my server. Maybe it is because I use lighttpd as webserver?
Funny is that I can access my calendar data with my browser.

Best,
Ulrich

**Comment by timoberger** [comment] 2013-08-26 11:00
are you able to create a dump of your network traffic with "Charles Proxy"?
http://www.charlesproxy.com/
if so, please send to timoberger@users.sourceforge.net, not to this list

**Comment by ulno** [comment] 2013-08-26 16:01
Just sent pm with dump.

Ulrich

**Comment by timoberger** [comment] 2013-08-26 18:44
the server responses with the status "501 - not implemented".
owncloud uses SabreDAV for the integration of all DAV-protocols.

I found a reference [1] where Evert Pot the maintainer of SabreDAV stated, that "The 501 error here is emitted by lighttpd, not sabredav. The request actually never reaches sabredav in this case."
Someone states later, that he fixed the problem with the version 1.4.31 of lighttpd.

the problem is on server side -> closing this issue

[1] https://bugs.kde.org/show_bug.cgi?id=318641

**Closed as completed by timoberger** 2013-08-26 18:44 UTC
Labels: server incompatibility

**Comment by ulno** [comment] 2013-09-22 10:48
I have finally managed my migration from lighttpd to nginx . I confirm that I now can get events created on owncloud calendar on my android device.

**Comment by timoberger** [comment] 2013-09-22 11:22
This sounds great. and now try my latest alpha and test the 2 way sync. :-)

**Comment by ulno** [comment] 2013-09-22 16:34
Yes, I am using 1.8-alpha-4 and it seems to work both directions (mainly). There seems to be an issue with the way the new Android 4.3 calendar is handling timezones. I will further investigate and report probably in another issue (but I have the feeling it's not caldav's fault).

Thanks a billion for this progress so far.

ulno

**Comment by gluhovsky** [comment] 2016-09-07 19:41
Same problem with server url: http://calendar.mail.ru

**Comment by brylie** [comment] 2017-03-16 03:35
I started seeing this error recently on our Nextcloud instance. Things worked previously, and I made no changes to the client or server configuration.

What server issue might be causing this problem?
