### ISSUE TITLE
adapter v1.3 currently not working with owncloud on android 4.1.2

### ISSUE THREAD

**Issue by ghost91-** [gggard/AndroidCaldavSyncAdapater#9] opened 2013-02-05 07:09 UTC
When the sync adapter is checking the connection it shows the message "Invalid server answer, check URL".

**Comment by gggard** [comment] 2013-02-05 12:48
Thanks for the report, I am currently loking at a workgin owncloud install for testing what's the problem is, if you can provide me a test account on your install, do not hesitate !

Hopefully, it will be linked with #6 and linked to a very special behaviour of davical (the sever it has been developped against), but not sure.

**Comment by chspnk** [comment] 2013-02-07 13:55
Hey gggard, if you like I can give you a test account at my owncloud installation..(?)

**Comment by modelno1** [comment] 2013-02-07 16:48
I have the same "Invalid server answer, check URL" problem when trying to connect to iCloud server.

**Comment by gggard** [comment] 2013-02-07 19:25
chspnk : it would be very usefull indeed that I have access to a test account ! Thanks !

**Comment by chspnk** [comment] 2013-02-07 20:08
gggard: Tell me how to send you the credentials, I'm new to github. Can't find a possibility to send a message..
[update] found your gmail address, will send it to this one. ;)

**Comment by ghost91-** [comment] 2013-02-10 18:25
It's still not working for me

**Comment by chspnk** [comment] 2013-02-10 22:00
yep, same to me @gggard did you test it on my owncloud install? did it work? btw, no problem ;)

**Comment by gggard** [comment] 2013-02-11 09:59
chspnk : I have tested on your owncloud install using the url : 
http(s)://server/owncloud base/remote.php/caldav/principals/user_name
do you use the same url scheme ?

**Comment by chspnk** [comment] 2013-02-11 10:38
gggard: ah ok, this is the iOS/iOS X Link - I used the CalDAV-link given by owncloud for each calendar http(s)://server/owncloud/remote.php/caldav/calendars/user_name/calendar_name
Give me a sec, i'll try the other link...
[edit:] seems to work, now i have to see if i can change the colors of the calendars, as it is quite confusing having all appointments in the same color (i have several calendars, e.g. for birthdays, private, one of my girlfried, etc.) will try it this evening, have to work now ;)

**Comment by gggard** [comment] 2013-02-11 13:36
By the way I opened enhancement #18 to be able to get as input also the direct calendar uri

**Comment by gggard** [comment] 2013-02-12 08:28
OK happy it is working for you, I close the issue

**Closed as completed by gggard** 2013-02-12 08:28 UTC
Labels: bug, server incompatibility

**Comment by mortee** [comment] 2013-02-12 19:35
It finally connects to my owncloud instance too - but only pulls events from the server, doesn't upload the event that I created on the phone.

**Comment by mortee** [comment] 2013-02-12 19:40
And also what I delete on the server doesn't disappear from the phone.

**Comment by ghost91-** [comment] 2013-02-12 20:51
With the iOS url, it's working for me, too, thank you :)
