### ISSUE TITLE
not working with zimbra

### ISSUE THREAD

**Issue by roidelapluie** [gggard/AndroidCaldavSyncAdapater#23] opened 2013-02-12 11:56 UTC
hello

iWhen I try to sync the application with zimbra, I have: "Invalid Server Answer, check url".

Here are the zimbra logs:

XXXX -  -  [12/Feb/2013:11:52:03 +0000] "PROPFIND /dav/roidelapluie/ HTTP/1.1" 401 0 "-" "-" 
XXXX -  -  [12/Feb/2013:11:52:03 +0000] "PROPFIND /dav/roidelapluie/ HTTP/1.1" 207 19798 "-" "-" 

With cadaver, I have only:

XXXX -  -  [12/Feb/2013:11:55:12 +0000] "PROPFIND /dav/roidelapluie/ HTTP/1.1" 207 727 "-" "cadaver/0.23.3 neon/0.29.6"

Any idea of the problem?

**Comment by gggard** [comment] 2013-02-12 14:23
Yes, it is linked to the issue #18, I will close this one and mark it as duplicate.
The problem is that Zimbra does not use principals url but have directly a url to the calendar,
detecting and supporting directly calendar URL is the objective of #18.

**Closed as completed by gggard** 2013-02-12 14:23 UTC
Labels: duplicate
