### ISSUE TITLE
Zimbra open source

### ISSUE THREAD

**Issue by jvb1** [gggard/AndroidCaldavSyncAdapater#103] opened 2013-09-19 19:05 UTC
Is zimbra open source supported for 2way sync?

**Comment by timoberger** [comment] 2013-09-19 19:22
i didn't test the current version against zimbra.
are you able to provide a test account for development? i would like to add this issue for the v1.9

do you already use zimbra with the sync adapter v1.7 or one of the 1.8-alphas?

**Comment by jvb1** [comment] 2013-09-19 20:38
I created an account without 1.7 
This works as an one way sync. I can see Zimbra but i can 't make changes.

**Comment by timoberger** [comment] 2013-09-19 20:44
there is a good chance that zimbra will work with v1.8
you can try my pre-release with 2 way sync.
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-3

please write a short report if you are testing the alpha.

**Comment by jvb1** [comment] 2013-09-20 07:30
I've tested v1.8 
This version works one way but in the other direction. 
I can connect with my agenda but I can't see any apointment that is in zimbra. 
If I make a new appointment in android, it appears in Zimbra. 
When I make some changes in the appointment on android, it doesn't change in Zimbra.
Let me know if I can test something else.

**Comment by timoberger** [comment] 2013-09-20 09:12
wrong thread, sorry

**Comment by timoberger** [comment] 2013-09-20 09:22
if i understand you right:
- you added a calendar to your android device?
- you are not able to see any events within this calendar?
- if you add a new event to your calendar (on android), this event is beeing synced to zimbra and is visible there?
- you are not able to update events on android?

**Comment by jvb1** [comment] 2013-09-20 09:35
I trie to explain better
- I've  installed v1.8
- I've connected with zimbra open source on my calendar using http://zimbra.url/dav/username/Calendar (this works using thunderbird lightning and zimbra
- I get the message sync ok.
- I see no appointments in my android phone (with v1.7 I get a copy of my appointments on my phone)
- I make a new appointment on my phone. This appears in my zimbra calendar.
- I make some changes in the appointment on my phone. On my phone it's OK but the appointment on Zimbra doesn't change. (I can't edit an appointment in zimbra using my phone)

**Comment by timoberger** [comment] 2013-09-20 09:54
please check which version in detail is installed (there is no version V1.8) on your device. see "settings" -> "apps" -> "caldav sync adapter"
please check if the acount is enabled to syncronize with the server (default value is "off")

did you add multiple calendars with multiple accounts? if so, please see issue #102 (i am currently working on)

**Comment by jvb1** [comment] 2013-09-20 10:07
It's v.1.8 alpha-3. I used the link you send me.
I only have added one calendar. 
syncronize is on. Last sync today 9:28

**Comment by timoberger** [comment] 2013-09-20 10:24
as i do not have access to a zimbra server, can you provide a test account for development to me? (timoberger@users.sourceforge.net)

**Comment by jvb1** [comment] 2013-09-20 16:40
Sorry
I'm not allowed to do that.
 I will ask our ICT.
If you wan't I can do some tests for you.

**Comment by timoberger** [comment] 2013-09-21 12:51
can you provide a network dump with charles proxy (http://www.charlesproxy.com/)?
the debug output could be helpful too.
please send this directly to me: timoberger@users.sourceforge.net

**Comment by jvb1** [comment] 2013-09-21 16:12
Do you have any instructions how to do this on android?

2013/9/21 timoberger notifications@github.com

**Comment by timoberger** [comment] 2013-09-23 10:42
it makes more sense if i debug zimbra by myself.
but this has to wait as i want to get the V1.8 out.

**Comment by roidelapluie** [comment] 2013-09-29 13:44
I confirm that appointments created in Zimbra do not appear on Android.

**Comment by roidelapluie** [comment] 2013-09-29 13:44
I tested against latest git revision.

**Comment by timoberger** [comment] 2013-09-29 15:06
@roidelapluie are you able to provide a test account?

**Comment by Ta1bolo** [comment] 2013-10-03 21:18
@timoberger Hi, I can provide you a test zimbra account. How can I transmit it in private?

**Comment by timoberger** [comment] 2013-10-04 10:34
@Ta1bolo great :) please send the account to timoberger@users.sourceforge.net

**Comment by Ta1bolo** [comment] 2013-10-04 10:42
@timoberger Done :)

**Comment by timoberger** [comment] 2013-10-04 14:07
there have been 2 issues.
- the sync adapter wasn't able to read the events proper (commit c463537)
- android creates an organizer within new events by default. the account name is used for the email address of this organizer. the method used at the moment (username@url) leads to an account name like username@maildomain@caldavserver which isn't optimal. zimbra answeres with the status code 500 when such a email address is used. (commit b43b583 with issue #108)

**Comment by timoberger** [comment] 2013-10-04 16:27
zimbra users have to:
- use the principal url (i.e. https://server/principals/users/username)
- set their email address as account name

this should be all.

**Comment by timoberger** [comment] 2013-10-04 16:41
i released the v1.8.1-beta.1 https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/v1.8.1-beta.1
test this with zimbra and give some feedback please.

**Comment by jvb1** [comment] 2013-10-04 20:07
Hi
In this version  i have 2 way sync between zimbra open source and android. That's good.
Sometimes it take some time before my appointments showed in my calendar.
To sync i have to open my settings and let the sync run.
How to change when sync is running. 

Nice work

**Comment by timoberger** [comment] 2013-10-04 20:12
the sync trigger is controlled by android itself. there is currently no way to change the sync occurrence.
@Ta1bolo are you the admin for the server you gave me? i would like to have a permanent account to check against.

i will close this issue. feel free to reopen if needed.

**Closed as completed** 2013-10-04 20:12 UTC
Labels: server incompatibility

**Comment by Ta1bolo** [comment] 2013-10-04 21:10
@timoberger Yes I am, no problem to let this account open to you for testing purpose.
I try 1.8.1-beta.1 and now it works for calendars created in Zimbra.
But I also have iCal subscription in Zimbra and, despite sync adapter find them, I can't see any events in Agenda. So, I add one to the test account, can you please watch where the problem is? Do you want me to create a new issue for this?

**Comment by djbarry** [comment] 2013-10-22 22:50
timoberger: caldavd, any URL combination which is actually recognized, results in a general sync failure.  I've got a test account set up for you if you would like to pursue it -- email me at don@donbarry.org for the credentials.  Thanks for working on this important tool!

**Comment by timoberger** [comment] 2013-10-23 06:32
@djbarry thanks for the offer. did you test your server with my latest release 1.8.1-beta.1 ?

**Comment by djbarry** [comment] 2013-10-23 06:49
On 10/23/2013 02:32 AM, timoberger wrote:

> @djbarry thanks for the offer. did you test your server with my latest release 1.8.1-beta.1 ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gggard/AndroidCaldavSyncAdapater/issues/103#issuecomment-26883336

Yes, with the same results as 1.8  -D

**Comment by timoberger** [comment] 2013-10-23 08:45
@djbarry i just realized that this is not zimbra.
please open a new issue for caldavd and describe the set up a little bit.

**Comment by timoberger** [comment] 2013-10-23 08:48
@Ta1bolo there is a bug within the beta.1
you have used french special chars and the sync adapter uses the decoded path where the encoded path should be used.

**Comment by timoberger** [comment] 2013-10-23 11:53
@djbarry your issue will be handled with #126

**Comment by LaHaine** [comment] 2013-10-28 14:16
With 1.8.1 beta-1 I can get 'my' Zimbra calendar using the principal url and I can add events to it. But I'd like to use a shared calendar as well. In 1.7 with the one way syncing, I'd add a CalDav account for every shared calendar with an URL like this: https://zimbratest.example.com/dav/lahaine@example.com/Gruppe%20von%20Doe,%20John/
That would be the calendar called Gruppe shared by my colleague John Doe. How can I access this calender with 1.8.1+

**Comment by timoberger** [comment] 2013-10-28 14:18
@LaHaine you will have to wait for 1.8.1-beta.2 or the official release of 1.8.1. sorry.

**Comment by Xoria64** [comment] 2013-10-31 16:44
Hi!
Thanks a lot! 
It's ok for me 2 way sync using   https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/v1.8.1-beta.1 on  Android 4.1.2 on Galaxy S2 and  our Zimbra server open source 7.7.2 .

Thanks!

**Comment by LaHaine** [comment] 2013-11-26 15:30
@timoberger: I can use two way sync with my personal Zimbra calendar, but I cannot add an entry to the shared calendar added with an URL like mentioned above. It would be nice to have a way to discover shared calendars like on the Zimbra web interface.
