### ISSUE TITLE
Calendar not updating with owncloud 5.0.6

### ISSUE THREAD

**Issue by dodger-one** [gggard/AndroidCaldavSyncAdapater#61] opened 2013-05-16 10:27 UTC
Hi,
I've began using your app recently (yesterday) and I've tried to sync with my owncloud instance.
The problem is that it sync only one way: from the server to the android device.
If I modify anything on the server, it work; the reverse operation does not work...
I've been looking my webserver logs (nginx) and I see that it only request changes to the server, the application does not push new changes.
Of course with other devices (thunderbird+lightning) it works fine!
Maybe I forgot something but I doubt cause there aren't a lot of setting ops.
I've not receiving any error (unless it report the error internally and I can't visually see it).
Thanks!

**Comment by nodiscc** [comment] 2013-06-07 17:30
Hi, this is a duplicate of https://github.com/gggard/AndroidCaldavSyncAdapater/issues/39
Two way sync is not available yet (only pull from server).

You should watch the other issue thread and close this one...

**Closed as completed** 2013-08-23 10:04 UTC
Labels: bug, duplicate

**Comment by timoberger** [comment] 2013-08-25 10:48
i have set up a test version.
please see #86
