### ISSUE TITLE
Wrong URL 

### ISSUE THREAD

**Issue by ghost** [gggard/AndroidCaldavSyncAdapater#82] opened 2013-08-22 08:15 UTC
Installed today via F-Droid on my "Samsung GT-I8190 Galaxy S III mini". While i try to setup with ownCloud 5.0.10 i get a "Wrong URL" error.

My URL attempts (with and without trailing slash):
- https://mysubd.blahblah.de/remote.php/caldav/principals/myuser
- https://mysubd.blahblah.de/remote.php/caldav/calendars/myuser/defaultcalendar
- https://mysubd.blahblah.de/remote.php/caldav

Nothing worked so far. Could there be a problem with subdomains? Is there a logfile where i can see more details?

Android 4.1.2 + CalDAV Sync Adapter 1.7

**Comment by jonas2515** [comment] 2013-09-01 15:11
My problem is exactly the same. Same Android version, same Owncloud version and the same version of CalDAV Sync Adapter on my HTC One v with CyanogenMod.

I've tried it with a top level domain and a valid ssl certificate.

Please fix this bug.

**Comment by timoberger** [comment] 2013-09-01 15:18
please check if you are able to access this owncloud calendars
user: test
pass: test
http://demo.owncloud.org/remote.php/caldav/calendars/test

**Comment by timoberger** [comment] 2013-09-01 16:09
this url should also be fine (checked this right now)
http://demo.owncloud.org/remote.php/caldav/principals/test

**Comment by jonas2515** [comment] 2013-09-01 16:24
Your urls are working for me, too. But with my OwnCloud it doesn't work.

Maybe the problem is the https. When I type in my URL with http it says unknown error, with https it says wrong url.

**Comment by timoberger** [comment] 2013-09-02 10:23
i do not have access to a calendar server that is using https.
can you contribute an account for me?

**Comment by jonas2515** [comment] 2013-09-02 14:28
thats no problem but how can I tell you my domain, because I don't want everyone to see it.

**Comment by timoberger** [comment] 2013-09-02 14:33
you can contact me at timoberger@users.sourceforge.net

**Comment by timoberger** [comment] 2013-09-02 15:26
i can confirm this issue.
the server returns 404 - file not found

i have to got into further details. this will take some time. am i allowed to use the account for some days?

**Comment by jonas2515** [comment] 2013-09-02 15:41
of course, thank you for working on the problem.

**Comment by timoberger** [comment] 2013-09-03 19:52
the server seemed to route the request based on the http-header "host" to the vHost. due to the missing header, the request didn't reach the correct vHost and the server responded with 404 - file not found.

**Comment by jonas2515** [comment] 2013-09-03 20:09
Can you implent sending the http-header, so the app works with openshift hosted servers, too.

**Comment by timoberger** [comment] 2013-09-04 07:26
this will be fixed within my next release.
i will close this issue. feel free to reopen it when needed (e. g. the fix didn't work for you)

**Closed as completed by timoberger** 2013-09-04 07:26 UTC
Labels: bug
