### ISSUE TITLE
Doesn't work with iCloud

### ISSUE THREAD

**Issue by modelno1** [gggard/AndroidCaldavSyncAdapater#25] opened 2013-02-14 11:49 UTC
Gives me "Invalid server answer, check URL". Running adapter 1.4 on ICS 4.0.3.

**Comment by gggard** [comment] 2013-02-16 11:49
Perhaps it is linked to #18, let wait for the new version and see if it fixes you problem

**Comment by gggard** [comment] 2013-02-19 12:57
Mark it as duplicate of #18, if needed reopen it !

**Comment by modelno1** [comment] 2013-02-19 18:01
After updating iCloud still gives me "Invalid server answer, check URL".

**Comment by krzd** [comment] 2013-04-07 21:48
Works fine for me. I had the same message first when I entered the full address without trailing slash. I used the full server address in the form https://pXX-caldav.icloud.com:443/YY/principal/, replace XX and YY with appropriate details which I obtained on my mac in ~/Library/Calendars/...

**Comment by gggard** [comment] 2013-04-08 20:38
Thanks krzd for the report, I close

**Closed as completed by gggard** 2013-04-08 20:38 UTC
Labels: server incompatibility
